### ISSUE TITLE
The new feature to use https in outgoing webhook fails in some occasions

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#1081]
Unclear why this happens. Should be better error handling at least?

```
2024-04-12T05:27:30.941Z error: WEBHOOKOUT 1 message: unable to verify the first certificate
2024-04-12T05:27:30.941Z error: WEBHOOKOUT 1 stack: Error: unable to verify the first certificate
    at AxiosError.from (file:///home/goran/code/butler/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///home/goran/code/butler/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:530:35)
    at eventHandlers.<computed> (/home/goran/code/butler/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///home/goran/code/butler/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendOutgoingWebhook (file:///home/goran/code/butler/src/lib/webhook_notification.js:262:34)
```

**Comment by mountaindude** [comment]
Added better and more informative error logging when outbound webhook calls fail.
