### ISSUE TITLE
Empty fileCopyApprovedDirectories entry in YAML config file gives runtime error

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#152]
**Describe the bug**
In the YAML config file, if `fileCopyApprovedDirectories`or `fileMoveApprovedDirectories` or `fileDeleteApprovedDirectories` is empty, a runtime error will happen: 

```bash 
D:\tools\butler-dev\globals.js:207
    config.get('Butler.fileCopyApprovedDirectories').forEach(element => {
                                                    ^

TypeError: Cannot read property 'forEach' of null
    at Object.<anonymous> (D:\tools\butler-dev\globals.js:207:53)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\tools\butler-dev\butler.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

Make Butler more tolerant to various config file settings.
Specifically, having just a header but no entries in a list should be ok.

For now the workaround is to remove those headings from the config file if they cause troubles.

**Comment by mountaindude** [comment]
Released as part of https://github.com/ptarmiganlabs/butler/releases/tag/v5.3.0
